// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBExU1fc1UfSN6w7F5mgj9pORwo4Db_Isc',
    appId: '1:104316612933:web:b300b18a0e503587738e2c',
    messagingSenderId: '104316612933',
    projectId: 'cognifict',
    authDomain: 'cognifict.firebaseapp.com',
    storageBucket: 'cognifict.appspot.com',
    measurementId: 'G-YFCFF33CV7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLj0auvwbdYr8m4rn8PLC0nO2THZ3Ot5c',
    appId: '1:104316612933:android:b5bc8e0be934bd84738e2c',
    messagingSenderId: '104316612933',
    projectId: 'cognifict',
    storageBucket: 'cognifict.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3o7-VsqiNULP72mHiGhIaQCpgqBE_Dfc',
    appId: '1:104316612933:ios:5a132176227c4acc738e2c',
    messagingSenderId: '104316612933',
    projectId: 'cognifict',
    storageBucket: 'cognifict.appspot.com',
    iosBundleId: 'com.example.cognifict',
  );
}
